### PR TITLE
Fixed and optimized split methods

### PR DESCRIPTION
**Pull request by Guiorgy**
I also replaced the custom `InvalidCountExceedingBehaviourException` with the builtin `ArgumentException` since that is what `string.Split` throws when `StringSplitOptions` is invalid. If that is unacceptable, the commit can be dropped.

I also renamed the `CountExceedingBehaviour` options to, what I think, better explains them. Also reworded the summary comments. Again, if you disagree with that, you may drop that commit.

There's 1 more gatcha in `string.Split`: If `separators` (`delimiters` in `SplitAny` in our case) is an empty collection, the function automatically assumes that we wish to split the string with white spaces:

> If the separator parameter is null or contains no characters, white-space characters are assumed to be the delimiters

Sigh... So there are several ways to handle this:
- Ignore it, and throw an exception if delimiters is empty.
- Do what .NET does, or in other words, go through the source span first, get all whitespace characters present in a remporary array (which **will** allocate -_-), and then go through the source span once more to split it.
- Write an alternative implementation where instead of checking if a character from source span is part of delimiters, we check if the character is a whitespace character using `char.IsWhiteSpace()`. Though I am assuming this is slower than the option above, otherwise why would .NET do it differently.
- Any other thoughts?

### CODE REVIEW

**Comment by dragon7307** [comment]
Looks good at first glance. I'll review, slightly adapt the style to better match the project, and merge it.
I originally created, that custom exception to avoid having to throw two different exceptions for before and after .Net 7, but if `string.Split` uses `ArgumentException`, then this sounds good to me. I'll look into the behaviour for null or empty delimiters as well, though I would prefer not to throw an exception. We'll see...

**Comment by dragon7307** [comment]
`count` and 'options' are in the right order on dev.

**Comment by dragon7307** [comment]
Also, I have looked a bit more to the tests you've written and I believe, we should probably merge them into a feature branch of dev with the `src` files from dev and the `tests` files from your pr.

**Comment by Guiorgy** [comment]
I have a local branch with uptodate commits from the `dev` and `tests` branch for testing. Do you want me to merge the `dev` branch into `tests`, or make a separate branch for that?

**Comment by dragon7307** [comment]
I have a branch in this repo, called "_feature-unit-testing_", in which I have adapted your `tests` branch as of yesterday to better suit the project's style and have brought it up to date with dev. Just take a look at the changes i made. if you agree with them, we have two options: we either merge any eventual changes  you have locally into this branch and continue working on this branch, which is based of off `dev`, into which it will eventually be merged, or you push any changes you have made to `tests` to your fork and we then merge my updated branch with yours into your fork. 
If you don't agree with the changes I made, then yes, do as you propose, and merge dev into a branch created from tests.

**Comment by dragon7307** [comment]
Also, unless I have gotten something dramatically wrong, we could refactor the monster that is `GetAllStringSplitOptions` to the following: 

```csharp
public static StringSplitOptions[] GetAllStringSplitOptions()
{
    return (StringSplitOptions[])Enum.GetValues(typeof(StringSplitOptions)); 
}
```

**Comment by Guiorgy** [comment]
I'll look into them, and probably just merge them into the `tests` branch. It was going to be merged with `dev` eventually anyways.

As for the `GetAllStringSplitOptions` method, the problem here is that `StringSplitOptions` is an enum marked with the `Falgs` attribute, which means you can combine options with the or (`|`) operator.

Try running this:

```cs
var options = (StringSplitOptions[])Enum.GetValues(typeof(StringSplitOptions));
Console.WriteLine(string.Join(", ", options));

var options2 = GetAllStringSplitOptions().Select(o => o.ToString().Replace(",", " |"));
Console.WriteLine(string.Join(", ", options2));
```

The output should look like this:

```
None, RemoveEmptyEntries, TrimEntries
None, RemoveEmptyEntries, TrimEntries, RemoveEmptyEntries | TrimEntries
```

While `Enum.GetValues` does get all defined enum values, it does **not** return their combinations when the enum is marked as flags.

The one I wrote was the simplest I could find, since the alternative would be trying to generate all permutations of the enums returned by `Enum.GetValues`, and remove duplicates (since `Enum.GetValues` also returns `None`, and `None | TrimEntries` is the same as `TrimEntries`).

If you have an alternative, don't hesitate to suggest.

**Comment by dragon7307** [comment]
How about just hard-coding the values into an array?? They are unlikely to soon be changed and the current method seems overkill for such a simple purpose for a test suite.

**Comment by Guiorgy** [comment]
An alternative would be to manually hardcode all possible values, but you'd have to remember to update them if a new one was ever added. I wanted to make something that (hopefully) doesn't need to ever be modified again.

The only reason why that code wouldn't work anymore (as stated in the comment next to the `Debug.Assert`), is if a new option was added that for some reason skipped a bit (for example, `TrimEntries = 1 /* binary 001 */, SomeNewOption = 4 /* binary 100 */`), which shouldn't happen (fingers crossed).

If you prefer hardcoding those values, I'm fine with changing that.

**Comment by dragon7307** [comment]
Then let's leave it that way!!

**Comment by Guiorgy** [comment]
Run into another edge case when expanding the fuzzing with parameterized (`[Theory]`) testing.

If the separator span is empty in `Split(source, delimiter)` the enumeration never stops and keeps returning empty spans forever. Yikes.

**Comment by dragon7307** [comment]
The current implementation tests for the delimiterlength in every iteration of `Move`, This is unnecessary, since `delimiter.Length `doesn't change. The check should probably be in the constructor instead.

**Comment by dragon7307** [comment]
One could at least do the comparision once in the constructor and the have a field like `DelimiterIsEmpty`, which is set in the constructor to `delimiter.IsEmpty` and then checked.

**Comment by Guiorgy** [comment]
That is already basically what I do thout?

```cs
DelimiterLength = Delimiter.Length; // cached in constructor
...
if(delimiterIndex == -1 || DelimiterLength == 0)
```

The only difference is that instead of a boolead I am comparing an int to 0, but considering booleans are basically an int that is compared to 0 to check state, there's no real difference.

**Comment by dragon7307** [comment]
Yes, but in theory your version should trigger an  invocation of the comparision operator and thereby the `Equals` method.
And sure, this is something that the compiler will optimize away, but since we cannot predict which compiler the consumer of this library will use, it is better to stay stafe, because maybe the official compiler optimizes it, but maybe someone uses **mono**, and maybe mono doesn't optimize this, or **IL2CPP** doesn't. Also,  a boolean is in **C#**, unlike in say **C**, the size of a byte not of an int.  

As you can see [here](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPof7+ACAmAjALABQJMEYApigA4QDGlABAMp0wCiAHgpTClAD2/AHQcYAVyoAnCAkHSUJAN4km6ptgDMTaZQBmTFAmkT6CVuzYAbKAhaUAjhL6NxUyrPnS1G1cQ1ApgAlSggAEwB5GGsATzYIGAAeWAQAPktEgG5fIN0w8OE4kILouITk1IyAEUpbMDtPHIC8/Iii2KZUplr6xukAGT4AcwQAC2bWpmBBQWsmdxk5IRhq4Upm3KCAel2mJJQpSGlYtK3A3e2mAHFKBBQmceY6yioYC1hHseZ6OetKcwrJhyL4/CTSPTvJg0QQCBBAwSGJ5MPgeLwKETnDSXfbbQ5gY6nLHqbQlCJleLsFLvDIAYXBkIsyiYwzuWS67085HmKDZTAAviRiUwcQcjhATmcWnkcbThMZTOYHhB9ryfnp9ABeABEFRsdgczlclEWnjkCmUABV+drthl9NJBGBgUZ2MCYOEXeE6lAGrxpCJVSZhMM0hSmL9+B4vlAHngvo6JMMxqrKOqDDrQuSYpTEtxePwVigRPqEFb+QAKLNRHMVctwMk18rscsASltaSSeODMFDmOlOz2XfxhKlU1FdFkzvIVB1KEE4MY2rSlu+qfTWu11YpdetHcegmmzFotgQIi7k4oY9aE4lFCYM8oOu9fX9y4AgjAOcZEowmIj1wjDVM1KWsWz3O0vhBF9fTsB5kQANwlIQJAeQ5gAAWm3MDEgeT4kkvMANQfCgn21edF0oDtz22QjrzyUk9RoU9DRcGA3EkJZvCrUDm0Sal0iMBdpEYBtsL4yoaSYGC/U8VthX8KZAgqJhNSEyjJiU9Relg/1VOkn1ZOkTStJ0oyhl7cZ9LM/oRAs0YJmFQJTS8FY1hgZg1P0CBrF5EylPpCE+AsNTvW8iRrAQfzAkFUgBwuIcRwlIl4uxPZQgQcF+HdFFOLNbwoI+f05GoBMF2TF1fmsf5AWEftxyHPFxUlYVST0doc0yGBS1Y40XPNaQbjufruNbdQFKcjRsAAdhjFBoo0WLhVFJKWtS9QcXfcIkPY0rkVRLiFAPUEH0oHgUX+N4LAA5Eqpq+E6uWxrVpShqriSGaUE7NUmGsRJhgAdwUcIdRMFx9ygJE1wO/KjoB1AjDMRgUBQfQIuKCIdsYT15BOjzzpeK72QONNfv+oHpBB7VvN8qjIMhk6YfRQaxgRugUcoHHoY9f8oZ+P4AQemAaM++iglJGY5iYABZQQEMoAA5M6EAreT1qYRStK6fQKxGtz1jVrWNcmhjZppvyTYFIV1cCboZP6ABJD0zv0ioRCd70uEiHWbP9VtNhtjRIYre3/Q9l3NTUjD8CYdB0B6Qz+nsqzI6YAAGQ2tc1o31D14R3M8x5TA2a2c40QLGVd9gA7LklZrBkvA/UJam6YCvgqrxIAG0RBEUPPHDrgAF0FryFS1IqLuQ8TsPna4JgAGoE9fTxk7GVte5H0utZmouXFHq2B1i/kgA===), in **jit asm** a `dword` (4 bytes) is used for the comparison for the int .   On the other hand, [here](https://sharplab.io/#v2:C4LghgzgtgPo/38AEBMBGAsAKEwOzFAphAA5gDG+ABAMonYCiAHsPthAJYD2rAdHdgK4EATmGAchETAG9MFORVnyEAZgpD8AMwoRgQ/qWDVaNADZtgVfAEd+Lcn0H4RYoYrkyM8rxQBK+MAAmAPLYJgCeNGDYADxs2MAAfEZRANxybt7qgVzhvv7BoRG0sfFJACL4ZlDmTmkKnt5yWQE5YRQARhwcJhQVVTVCAJIQdFBEwGEpGV6d3RQOwqKc2GVc+FNYDY0A9LsU0RCCUGBCYQnT8rvbFADi+MAQFMAAFpSV+ATxFHFPrxSk3RM+AMywool+lFI/CE6i+RA47GAoI4WhebwEixc3Auciu+22hygx1O5y23hUeUCIXCkRicUSFAAwtDYYYpBQAOb3NL0py4HoQbkUAC+mBxFDxByOJzO4rxjK4Oj0BkeYH2gsh6g0AF4AES00zmSw2Oz4BZOUTiKQAFWFuu2SQ0Qg4UDB2loYOwATdAUqbGqzCE3HVui4HIS1LaANYjl+bEeyF+zv4HOe6vwms0er8VMKtMYzFYywg3ENwBtwoAFDmCjTaBWADSU2tFKIVgCU9oS0QJoew4exZK8koJ0pJcr20RIIlduAIeogHGh5F1CWtfwOGf+Wuz+UjtIrXaeHA6lGIZmA3B707wpMauMnN9neHwet9/UDq4AgthvqxgFE5AUCi6aZjquo1vu9a2keLzgu+/rmI8aIUAAbicnD8I8hztAAtJBea0I8PxTiceBahQc6vrqi7LvgXZXtsT53veFIGkQF7GrY2D2BiFouNWe6EVEJQMrRQjkE2BF1iJ9JJAhAZOO24oePe3i0hQ2raEuEnrOKXh9IhgaaRQCkDBsakGX6ilDCMYwTCZhk2dwwyjOMkz6fI5rOMsqzYJQWkaGAJiChZllyMyMIsIYWm+kF/AmMAYWNKKmxqZKhLErKQ6XHsfjANCrCehQLCOM44i/OCAyiIQSZLqmboAiYQIglwg7pZOo5EjKLGNBSzStMk2BllxpreZaQi3Pc40CcpOXuJ5cgIAA7HGEDJd4qUTtcUrdeO80SnsX4BOhPG1ShpWYhVYgQpR+BMCVQKfIYIEoU1LVIm1234plPXfdEK0QN2GoUCYUQcgA7uIAR6rothHmwqJ/Jd/EVRDkDaPo5AQBAGgJbkgSneQ3o3Sh/kPe8z1pJulBg/2UNCDDupBSF9EOt8SPomVE0UM8GMkDj+Ak8jXrAZz/yAsCn3YIxgO9eSqizD0ACyHCofgABy93AJWc1qap4Uc5WM2+WseuGwbhtKKtLOhYtIpigdXj0qZ1kDIMXr3SZtIuZ7DBBBolZOQM7YbPbiOVmZgYe76DCaVpuEoBQMAwL0bvR3Z7nm+FltW/MfE+VwfkBU8eh6WlecRSy0Xe7QYdO6xq1w+XVtbQ3VdRV8Wm0gA2tw3BR04Mf3QAuhtakad3tA95H6dD37FAANRpx+TjcAAMiwHIvO2/dj47VsraXtjj/IqVeKlwpAA=) with the **boolean**  approach, a `byte` is used. That is a difference in memory allocation. Now, whether this will actually result in a measurable performance difference is debattable, but as a matter of fact, they produce different **jit asm** and hence  work differently. The **asm** is in favour of using the boolean. 
 
Here are the screenshots top to bottom, on the first is the approach with (DelimiterLength) and the second DelimiterIsEmpty:    

image
image


  
And yes that is micro optimization, but so is the mere concept of Spans in C#.  
Also, the example uses an int instead of generics, as generics can't be jit compiled by sharplab in c# and dotnet.

**Comment by dragon7307** [comment]
I see, I agree it isn't that important now, I get the idea of the antonyms, however I felt that 'append' is more descriptive as to where the remaining elements are actually included (they're appended to the last element). The downside of this approach is that the antonym is not necessarilly a good fit for the contrary behaviour. There is no need to Update the pull request right now as the differences are growing so complex that I will need to merge it into a helper branch and then resolve many conflicts.  

The final decision on the name is going to be made before the release of version 1.3.0, because I do not want to introduce a breaking change later on.

**Comment by Guiorgy** [comment]
There's 1 more thing missing in the current implementation. All the Span Split Enumerators work and return `ReadOnlySpan`, even if the source is a `Span<T>`. This means that the following is impossible:

```cs
char[] source = "Lorem ipsum dolor sit amet...";

// Split source by space and capitalize the first letter of every word
foreach (var word in source.AsSpan().Split(' '))
{
    if (word.Length == 0) continue;

    word[0] = Capitalize(word[0]); // impossible, since word is a ReadOnlySpan<char>
}
```

To fix this, we'd need to duplicate every split enumerable and make it work with normal mutable spans, and update all extension methods and tests. We could do that now, or maybe try to make a source generator first to not have to do all that manually?

**Comment by dragon7307** [comment]
That seems like a job for the to be source generator

**Comment by Guiorgy** [comment]
I also added a check for validity of `StringSplitOptions`, which throws an exception when invalid. This is to copy what `string.Split` does.

**Comment by Guiorgy** [comment]
We should decide what are the final names for `CountExceedingBehaviour`, so I can fix the 2 PRs.

**Comment by dragon7307** [comment]
I am pretty set on `AppendRemainingElements` and `CutRemainingElements`.

**Comment by Guiorgy** [comment]
> I am pretty set on `AppendRemainingElements` and `CutRemainingElements`.

Ok, on it

**Pull request merged**
